version: 2
jobs:
  build:
    working_directory: ~/Android-Demo-1
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies 
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;arm64-v8a" && echo "no" | avdmanager create avd -n Nougat -k "system-images;android-24;default;arm64-v8a"
      - run:
          name: Create SD Card 
          command: mksdcard -l e 512M mysdcard.img      
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd Nougat -noaudio -no-boot-anim -no-window -accel on -sdcard mysdcard.img
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: |
            ./gradlew spoonDebugAndroidTest
         
      - store_test_results:
          path: app/build/outputs/androidTest-results/connected

      - store_artifacts:
          path: app/build/custom-report-dir/debug
