version: 2
jobs:
  build:
    working_directory: ~/Android-Demo-1
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies 
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  test1:
    working_directory: ~/Android-Demo-1
    docker:
      - image: circleci/android:api-26-alpha

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator 1
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"

      - run:
          name: Create SD Card 1
          command: mksdcard -l e 512M mysdcard22.img      
        
      - run:
          name: Launch emulator 1
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on -sdcard mysdcard22.img
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: |
            ./gradlew spoonDebugAndroidTest
         
      - store_test_results:
          path: app/build/outputs/androidTest-results/connected

      - store_artifacts:
          path: app/build/custom-report-dir/debug
  test2:
    working_directory: ~/Android-Demo-1
    docker:
     - image: circleci/android:api-26-alpha
    step:
      - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Setup emulator 2
        command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test1 -k "system-images;android-22;default;armeabi-v7a"          
    - run:
        name: Create SD Card 2
        command: mksdcard -l e 512M mysdcard26.img  
    - run:
        name: Launch emulator 2
        command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test1 -noaudio -no-boot-anim -no-window -accel on -sdcard mysdcard26.img
        background: true
    - run:
        name: Wait emulator
        command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
          adb shell input keyevent 82
    - run:
        name: Run Tests
        command: |
          ./gradlew spoonDebugAndroidTest
       
    - store_test_results:
        path: app/build/outputs/androidTest-results/connected

    - store_artifacts:
        path: app/build/custom-report-dir/debug

     

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
